// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3XO1yPa-mfdLRiqqhk4GPLk1fb-dRK4M',
    appId: '1:1023175142321:web:e31b595ff25a23d880eb90',
    messagingSenderId: '1023175142321',
    projectId: 'svinefarm-5823e',
    authDomain: 'svinefarm-5823e.firebaseapp.com',
    storageBucket: 'svinefarm-5823e.appspot.com',
    measurementId: 'G-GZY9BLD98K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApPt1a8XcOOYIVatxvO3KMWb4ofg0FjU',
    appId: '1:1023175142321:android:7a9f7087d94c43ad80eb90',
    messagingSenderId: '1023175142321',
    projectId: 'svinefarm-5823e',
    storageBucket: 'svinefarm-5823e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOgnRL6BM9dJLcvNcxxqGtGzDpZ7psw8',
    appId: '1:1023175142321:ios:a89d5063a52c991480eb90',
    messagingSenderId: '1023175142321',
    projectId: 'svinefarm-5823e',
    storageBucket: 'svinefarm-5823e.appspot.com',
    iosBundleId: 'com.example.svineFarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtOgnRL6BM9dJLcvNcxxqGtGzDpZ7psw8',
    appId: '1:1023175142321:ios:a89d5063a52c991480eb90',
    messagingSenderId: '1023175142321',
    projectId: 'svinefarm-5823e',
    storageBucket: 'svinefarm-5823e.appspot.com',
    iosBundleId: 'com.example.svineFarmApp',
  );
}
